# Generated by Django 5.2.10 on 2026-02-24 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_category_document_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='document_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='users.document'),
        ),
    ]
