# Generated by Django 5.2.10 on 2026-02-24 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_post_document_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='document_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='users.document'),
            preserve_default=False,
        ),
    ]
