# Generated by Django 5.2.10 on 2026-02-24 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_post_document_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='document_id',
            new_name='document',
        ),
    ]
