# Generated by Django 5.2.10 on 2026-03-02 15:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_document_id_post_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_login', 'User Login'), ('user_status_change', 'User Status Change'), ('document_create', 'Document Create'), ('document_view', 'Document View'), ('post_create', 'Post Create'), ('batch_action', 'Batch Action')], max_length=50)),
                ('target_type', models.CharField(choices=[('document', 'Document'), ('user', 'User')], max_length=20)),
                ('target_id', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
