# Generated by Django 5.2.10 on 2026-03-12 00:00

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_document_content_type_document_crawled_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('execution_mode', models.CharField(choices=[('queue', 'Queue'), ('thread', 'Thread')], default='queue', max_length=20)),
                ('job_id', models.CharField(blank=True, default='', max_length=255)),
                ('storage_root', models.CharField(blank=True, default='', max_length=1000)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('queued_at', models.DateTimeField(default=timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('total_log_lines', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('log_tail', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawler_runs', to='users.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]