server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://127.0.0.1:3100/loki/api/v1/push

scrape_configs:
  - job_name: journal
    journal:
      path: /var/log/journal
      max_age: 12h
      labels:
        job: systemd-journal
        host: backrail-vm
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: systemd_unit
      - source_labels: ['__journal__hostname']
        target_label: hostname
      - source_labels: ['__journal__systemd_unit']
        regex: '(backrail-web|backrail-rqworker|nginx)\.service'
        target_label: service
      - source_labels: ['__journal__systemd_unit']
        regex: '(backrail-web|backrail-rqworker|nginx)\.service'
        action: keep