global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: backrail-django
    metrics_path: /metrics/
    static_configs:
      - targets:
          - 127.0.0.1:7146

  - job_name: backrail-redis-exporter
    static_configs:
      - targets:
          - 127.0.0.1:9121

  - job_name: backrail-node-exporter
    static_configs:
      - targets:
          - 127.0.0.1:9100